apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-frontend
  template:
    metadata:
      labels:
        app: my-frontend
    spec:
      containers:
        - name: my-frontend
          image: my-frontend:latest
          imagePullPolicy: Never  # Important for local images!
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-frontend-service
spec:
  type: NodePort
  selector:
    app: my-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
